spec:
  serviceAccountName: jenkins
  containers:
  - name: jnlp
    workingDir: /home/jenkins/agent
    image: r.j3ss.co/img:v0.5.6
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
metadata:
  name: jnlp
  annotations:
    container.apparmor.security.beta.kubernetes.io/jnlp: unconfined
    container.seccomp.security.alpha.kubernetes.io/jnlp: unconfined
    