metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/jenkins-builder: unconfined
    # container.seccomp.security.alpha.kubernetes.io/jenkins-builder: unconfined
spec:
  serviceAccountName: jenkins
  containers:
  - name: jnlp
    workingDir: /home/jenkins/agent
    image: r.j3ss.co/img:v0.5.6
    imagePullPolicy: IfNotPresent
    # securityContext:
    #     rawProc: true
    #     privileged: true
    command:
    - cat
    tty: true