metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/jenkins-builder: unconfined
    # container.seccomp.security.alpha.kubernetes.io/jenkins-builder: unconfined
  name: jnlp
  labels:
    name: jnlp
spec:
  containers:
  - name: jnlp
    image: jmaclean/jenkins-jnlp-slave:3.40-1
    workingDir: /home/jenkins/agent
    securityContext:
      runAsUser: 1000
    resources:
      requests:
        memory: 128Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 1
  - name: jenkins-builder
    image: jmaclean/jenkins-builder:0.5.7
    workingDir: /home/jenkins/agent
    securityContext:
      runAsUser: 1000
      rawProc: true
    command:
    - cat
    tty: true